### PR TITLE
failed() method support

### LINKED ISSUE #28: Add support for failed method
Laravel's jobs support method `failed`. It is a very convenient way to process failed jobs.
It will be great to add support for this method

And there is no way to replace `ActionJob` in `QueueableAction`. So I cannot use my realization of `ActionJob` with `failed` method without overwriting `QueueableAction`

### PR DESCRIPTION
**Pull request by stancl**
Fixes #28 

Please review.

This can, hypothetically, be a breaking change: If someone had a `failed()` method, it would be executed on failures now. I'm not sure what's your approach with regards to semver, but I personally don't think this is an issue. Seems like an extremely rare case for this to be an issue.

### CODE REVIEW

File: src/ActionJob.php [hunk 1]
```diff
@@ -21,13 +23,20 @@ class ActionJob implements ShouldQueue
...
     public function __construct($action, array $parameters = [])
     {
         $this->actionClass = is_string($action) ? $action : get_class($action);
         $this->parameters = $parameters;
 
         if (is_object($action)) {
             $this->tags = $action->tags();
+
+            if (method_exists($action, 'failed')) {
+                $this->onFailCallback = [$action, 'failed'];
```
Comment (stancl) [inline src/ActionJob.php:38]: @freekmurze @brendt I'm not too knowledgeable about queues and serializing. I'd appreciate some input on this.

Originally, I wanted to set this property to a closure like:
```php
function (Exception $exception) use ($action) {
    return $action->failed($exception);
}
```

However, that resulted in an error saying that Closures can't be serialized.

So I went with this callable notation, but I'm not 100% sure that this is correct either.

What if `$action` is some unserializable object? Or an object that injects unserializable classes (like PDO connection instances, for example).

If that's an issue, then feel free to close this PR as I don't see any other way to achieve this. Either we need to store a Closure (which is impossible to serialize), or we need to store a reference to an object's method - and as an extension, store the object itself (which *might* be impossible to serialize?)

Or maybe we can just add a notice that the method works only with serializable actions.

Comment (brendt) [reply src/ActionJob.php:38]: > What if $action is some unserializable object? Or an object that injects unserializable classes (like PDO connection instances, for example).

It's a known constraint, there's little we can do about that. The same would happen if you'd try to store a closure or exception or something else unserializable on a job. Nothing we can do about that. So I'd say it shouldn't be a concern. I think it's a good solution!

File: tests/QueueableActionTest.php [hunk 2]
```diff
@@ -125,4 +127,18 @@ public function an_action_can_have_custom_job_tags()
...
+    public function an_action_can_have_a_custom_failed_callback()
+    {
+        Queue::fake();
+
+        $action = new ActionWithFailedMethod();
+
+        $action->onQueue()->execute();
+
+        Queue::assertPushed(ActionJob::class, function ($action) {
+            return $action->failed(new Exception('foo')) === 'foo';
```
Comment (brendt) [inline tests/QueueableActionTest.php:141]: Shouldn't we assert that the `failed` method was actually called when the action failed to execute?

Comment (stancl) [reply tests/QueueableActionTest.php:141]: I was trying to find the relevant Laravel code that calls the `failed()` method, but didn't succeed in that. So I decided to just go with this and sort of assume that Laravel correctly calls `failed()` on `ActionJob` as it's a normal queueable job.

If you want though, I can try to find a way to get the job to fail and we can set some global variable from the `failed()` method and then check for it in the test.

Comment (brendt) [reply tests/QueueableActionTest.php:141]: I think we need to be sure the method is actually called, not sure how to test it though…

Comment (stancl) [reply tests/QueueableActionTest.php:141]: If we're using the sync driver, I think throwing an exception from handle, catching it in the test and asserting that failed() was executed (I.e. set some global variable) should work. Will test that later today

Comment (stancl) [reply tests/QueueableActionTest.php:142]: @brendt Added that test now. See latest commit. Ready to be merged?

Comment (brendt) [reply tests/QueueableActionTest.php:142]: Nice! Thanks

**Comment by brendt** [comment]
Thanks! I'll fix the styleci issues on master

**Comment by brendt** [comment]
Released as 2.6.0: https://github.com/spatie/laravel-queueable-action/releases/tag/2.6.0
